### ISSUE TITLE
Cannot add a todo

### ISSUE THREAD

**Issue by ghost** [elgris/microservice-app-example#13] opened 2018-02-08 12:08 UTC
"Error occured while trying to proxy to: 192.168.42.129:30008/todos". Response code: 504

This happens on MiniKube

![image](https://user-images.githubusercontent.com/5337267/35972216-904f4a56-0cd9-11e8-8724-5c4dc3b1c473.png)

**Comment by elgris** [comment] 2018-02-17 12:03
Hi @eivantsov ! Thanks for your message, the problem is going to be fixed by #14

**Comment by ghost** [comment] 2018-02-17 12:40
I added a redis deployment and it worked even without log processor.

**Comment by elgris** [comment] 2018-02-17 15:02
@eivantsov that's true, it will work, but that's not the whole picture. And something needs to consume those messages from Redis.

**Comment by elgris** [comment] 2018-02-19 14:32
considering solved

**Closed as completed by elgris** 2018-02-19 14:32 UTC
